#!/usr/bin/env bash

exec 3>&1 &>/dev/null

if [ "$DPKG_MAINTSCRIPT_ARCH" == "iphoneos-arm64" ]; then
    DPKG_ROOT="/var/jb"
fi

SERV_AGENT="$DPKG_ROOT/Library/LaunchDaemons/com.82flex.noredirect.plist"

if [ -f "$SERV_AGENT" ]; then
    launchctl unload "$SERV_AGENT" || true
else
    launchctl remove system/com.82flex.noredirect || true
fi

sleep 2

if [ -f "$SERV_AGENT" ]; then
    launchctl load -w -F "$SERV_AGENT" || true
fi

killall -TERM runningboardd || true

exit 0